### ISSUE TITLE
[Bug] Randomly crash.

### ISSUE THREAD

**Issue by nathan130200** [redphx/better-xcloud#559]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [X] The bug doesn't happen when I disable Better xCloud script.
- [x] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Desktop

### Device

Browser

### Operating System

Windows 10

### Android app/Browser Version

Chrome 130.0.6723.119

### Better xCloud Version

5.9.5

### Game list

N/A

### Reproduction Steps

1. Open xcloud page `https://xbox.com/pt-br/play`
2. See "Failed to execute better xcloud" on your screen.

Devtools logs:

```js

Uncaught (in promise) Error: [Better xCloud] Executing workaround for Safari
    at Object.<anonymous> (userscript.html?name=Better-xCloud.user.js&id=97094dbf-52dc-43a0-b1ab-45ad520c6f2b:7978:168)
    at Pt (<anonymous>:10:89)
    at userscript.html?name=Better-xCloud.user.js&id=97094dbf-52dc-43a0-b1ab-45ad520c6f2b:1:90
    at window.__f__m3mch544.9fi (userscript.html?name=Better-xCloud.user.js&id=97094dbf-52dc-43a0-b1ab-45ad520c6f2b:1:317)
    at Pt (<anonymous>:10:89)
    at r.setMessageListener.r (<anonymous>:86:186)
    at <anonymous>:87:447
    at set (<anonymous>:96:130)
    at userscript.html?name=Better-xCloud.user.js&id=97094dbf-52dc-43a0-b1ab-45ad520c6f2b:1:29
    at Pt (<anonymous>:10:89)

```

Followed by other errors:

```js

client.f8aed30c.js:1 Uncaught (in promise) ChunkLoadError: Loading chunk 64580 failed.
(error: https://assets-www.xbox.com/xbox-web/static/js/64580.8191bf91.chunk.js)
    at n.f.j (client.f8aed30c.js:1:36132)
    at client.f8aed30c.js:1:5223
    at Array.reduce (<anonymous>)
    at n.e (client.f8aed30c.js:1:5201)
    at Object.lazyConfig (51433.d493d8d2.js:2:639596)
    at Ie._loadPartnerConfig (51433.d493d8d2.js:2:839734)
    at Ie._loadPartnerConfigIfReady (51433.d493d8d2.js:2:839442)
    at Ie._loadAllConfigs (51433.d493d8d2.js:2:840500)
    at Ie.initialize (51433.d493d8d2.js:2:837401)
    at async 51433.d493d8d2.js:2:870978


Uncaught (in promise) ChunkLoadError: Loading chunk 18132 failed.
(error: https://assets-www.xbox.com/xbox-web/static/js/core-partner.8b1dd307.chunk.js)
    at n.f.j (client.f8aed30c.js:1:36132)
    at client.f8aed30c.js:1:5223
    at Array.reduce (<anonymous>)
    at n.e (client.f8aed30c.js:1:5201)
    at Object.lazyConfig (51433.d493d8d2.js:2:639618)
    at Ie._loadPartnerConfig (51433.d493d8d2.js:2:839734)
    at Ie._loadPartnerConfigIfReady (51433.d493d8d2.js:2:839442)
    at Ie._loadAllConfigs (51433.d493d8d2.js:2:840500)
    at Ie.initialize (51433.d493d8d2.js:2:837401)
    at async 51433.d493d8d2.js:2:870978

Uncaught (in promise) ChunkLoadError: Loading chunk 86540 failed.
(error: https://assets-www.xbox.com/xbox-web/static/js/86540.577a7754.chunk.js)
    at n.f.j (client.f8aed30c.js:1:36132)
    at client.f8aed30c.js:1:5223
    at Array.reduce (<anonymous>)
    at n.e (client.f8aed30c.js:1:5201)
    at Object.lazyConfig (51433.d493d8d2.js:2:639607)
    at Ie._loadPartnerConfig (51433.d493d8d2.js:2:839734)
    at Ie._loadPartnerConfigIfReady (51433.d493d8d2.js:2:839442)
    at Ie._loadAllConfigs (51433.d493d8d2.js:2:840500)
    at Ie.initialize (51433.d493d8d2.js:2:837401)
    at async 51433.d493d8d2.js:2:870978



```

### Screenshot/video

![image](https://github.com/user-attachments/assets/02256986-d981-42e9-bb2c-7ca64f3534a5)

### Additional notes

Just hit to refresh page many times to make it work again.

**Comment by btncua** [comment]
### Did you follow steps on [🤓 button](https://better-xcloud.github.io/troubleshooting/) and also read request not to report this error because it is not a Better xCloud script problem?

**Comment by nathan130200** [comment]
There's no any useful information in that page to fix this problem. All steps described in the page already done and problem still persist. This is happening since last update.

As i've said before its a random error, sometimes happen, sometimes don't. Usually after many refreshes to page "fix" this. 

And no, its not tampermonkey problem, because the exception is thrown by better-xcloud: `}, CE("div", {}, CE("p", {}, t("load-failed-message")), $secondaryAction))), document.documentElement.appendChild($fragment), isSafari && window.location.reload(!0), new Error("[Better xCloud] Executing workaround for Safari");` this thrown the exception in call stack

**Comment by redphx** [comment]
> ⚠️ This is Tampermonkey's problem. Don't report it on Better xCloud GitHub.
